# -*- coding: utf-8 -*-
"""Copia de Project_EC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f7kh1kylh5Ag_3EQQpyzT01wwTzcpzT_
"""

!pip install pyDOE2
from pyDOE2 import lhs

def int_to_real_dom(num, domain):
  min_i, max_i = domain
  r = (num - min_i) / (max_i - min_i)
  return r

def real_to_int_dom(num, domain):
  min_i, max_i = domain
  value = min_i + num * (max_i - min_i)
  if isinstance(min_i, int) and isinstance(max_i, int):
      value = int(round(value))
  return value

def convert_individual(ind, to_real=True):
    real_rep = []
    N = max(layer_type_options.keys())  # Obtener el máximo índice de capa en el diccionario

    for i in range(0, len(ind), 4):
        layer_type_idx = ind[i]
        domain_layer_type = [0, N]

        if to_real:
            real_rep.append(int_to_real_dom(layer_type_idx, domain_layer_type))
            layer_type = layer_type_options.get(layer_type_idx, 'DontCare')
        else:
            real_rep.append(real_to_int_dom(layer_type_idx, domain_layer_type))
            layer_type = layer_type_options.get(real_rep[i], 'DontCare')

        # Decodificación basada en el tipo de capa
        if layer_type == 'Conv2D':
            if to_real:
                real_rep.append(int_to_real_dom(ind[i + 1], [4, 32]))  # Filtros
                real_rep.append(int_to_real_dom(ind[i + 2], [0, 1]))  # Stride
                real_rep.append(int_to_real_dom(ind[i + 3], [0, 3]))  # Activación
            else:
                real_rep.append(real_to_int_dom(ind[i + 1], [4, 32]))
                real_rep.append(real_to_int_dom(ind[i + 2], [0, 1]))
                real_rep.append(real_to_int_dom(ind[i + 3], [0, 3]))

        elif layer_type == 'SelfAttention':  # 🚀 Reemplazo de DepthwiseConv2D por SelfAttention
            if to_real:
                real_rep.append(int_to_real_dom(ind[i + 1], [4, 64]))  # Filtros
                real_rep.append(int_to_real_dom(ind[i + 2], [1, 8]))  # Número de cabezas de atención
                real_rep.append(int_to_real_dom(ind[i + 3], [0, 3]))  # Activación
            else:
                real_rep.append(real_to_int_dom(ind[i + 1], [4, 64]))
                real_rep.append(real_to_int_dom(ind[i + 2], [1, 8]))
                real_rep.append(real_to_int_dom(ind[i + 3], [0, 3]))

        elif layer_type == 'BatchNorm':
            real_rep.extend([0, 0, 0])

        elif layer_type == 'MaxPooling':
            if to_real:
                real_rep.append(int_to_real_dom(ind[i + 1], [0, 1]))
            else:
                real_rep.append(real_to_int_dom(ind[i + 1], [0, 1]))
            real_rep.extend([0, 0])

        elif layer_type == 'Dropout':
            if to_real:
                real_rep.append(int_to_real_dom(ind[i + 1], [0, 3]))
            else:
                real_rep.append(real_to_int_dom(ind[i + 1], [0, 3]))
            real_rep.extend([0, 0])

        elif layer_type == 'Dense':
            if to_real:
                real_rep.append(int_to_real_dom(ind[i + 1], [1, 512]))  # Neuronas
                real_rep.append(int_to_real_dom(ind[i + 2], [0, 3]))  # Activación
            else:
                real_rep.append(real_to_int_dom(ind[i + 1], [1, 512]))
                real_rep.append(real_to_int_dom(ind[i + 2], [0, 3]))
            real_rep.append(0)

        elif layer_type == 'Flatten':
            real_rep.extend([0, 0, 0])

        elif layer_type == 'Repetition':
            if to_real:
                real_rep.append(int_to_real_dom(ind[i + 1], [1, 4]))  # Número de capas a repetir
                real_rep.append(int_to_real_dom(ind[i + 2], [1, 32]))  # Cantidad de repeticiones
            else:
                real_rep.append(real_to_int_dom(ind[i + 1], [1, 4]))
                real_rep.append(real_to_int_dom(ind[i + 2], [1, 32]))
            real_rep.append(0)

        elif layer_type == 'DontCare':
            real_rep.extend([0, 0, 0])

    return real_rep

# Opciones de decodificación para otros parámetros
layer_type_options = {
    0: 'Conv2D',
    1: 'BatchNorm',
    2: 'MaxPooling',
    3: 'Dropout',
    4: 'Dense',
    5: 'Flatten',
    6: 'SelfAttention',  # Reemplazo de DepthwiseConv2D por Self-Attention
    7: 'DontCare',
    8: 'Repetition'
}

stride_options = {0: 1, 1: 2}
dropout_options = {0: 0.2, 1: 0.3, 2: 0.4, 3: 0.5}
activation_options = {0: 'relu', 1: 'leaky_relu', 2: 'sigmoid', 3: 'tanh'}

# Función para codificar los parámetros de la capa
def encode_layer_params(layer_type_idx, param1=0, param2=0, param3=0):
    """
    Codifica una capa en una lista en función del tipo de capa y sus parámetros.

    layer_type_idx : int : índice del tipo de capa según layer_type_options.
    param1         : int/float : filtros, neuronas, capas de repetición, etc.
    param2         : int : stride, número de repeticiones, etc.
    param3         : int : índice de activación o tasa de dropout.
    """
    return [layer_type_idx, param1, param2, param3]

# Función para decodificar los parámetros de la capa
def decode_layer_params(encoded_params):
    """
    Decodifica una capa desde su representación codificada en parámetros interpretables.

    encoded_params : list : [tipo de capa, param1, param2, param3].
    """
    layer_type_idx = encoded_params[0]
    layer_type = layer_type_options.get(layer_type_idx, 'DontCare')

    # Decodificar en función del tipo de capa
    if layer_type == 'Conv2D':
        filters = max(4, min(encoded_params[1], 32))  # Limitar filtros entre 4 y 32
        strides = stride_options.get(encoded_params[2], 1)
        activation = activation_options.get(encoded_params[3], 'relu')
        return {
            'type': 'Conv2D',
            'filters': filters,
            'strides': strides,
            'activation': activation
        }
    elif layer_type == 'BatchNorm':
        return {'type': 'BatchNorm'}
    elif layer_type == 'MaxPooling':
        strides = stride_options.get(encoded_params[1], 1)
        return {'type': 'MaxPooling', 'strides': strides}
    elif layer_type == 'Dropout':
        rate = dropout_options.get(encoded_params[1], 0.2)
        return {'type': 'Dropout', 'rate': rate}
    elif layer_type == 'Dense':
        units = max(1, min(encoded_params[1], 512))  # Limitar unidades entre 1 y 512
        activation = activation_options.get(encoded_params[2], 'relu')
        return {'type': 'Dense', 'units': units, 'activation': activation}
    elif layer_type == 'Flatten':
        return {'type': 'Flatten'}
    elif layer_type == 'Repetition':
        return {
            'type': 'Repetition',
            'repetition_layers': int(encoded_params[1]),
            'repetition_count': int(encoded_params[2])
        }
    elif layer_type == 'SelfAttention':
        filters = max(4, min(encoded_params[1], 64))  # Atención con 4-64 filtros
        attention_heads = max(1, min(encoded_params[2], 8))  # Máximo 8 cabezas de atención
        activation = activation_options.get(encoded_params[3], 'relu')  # Activación opcional
        return {
            'type': 'SelfAttention',
            'filters': filters,
            'attention_heads': attention_heads,
            'activation': activation
        }
    elif layer_type == 'DontCare':
        return {'type': "DontCare"}

    return None

# Ejemplos de codificación y decodificación
encoded_conv2d = encode_layer_params(0, 16, 0, 0)  # Conv2D con 16 filtros, stride 1 y activación ReLU
decoded_conv2d = decode_layer_params(encoded_conv2d)
print(f"\nCodificación real de Conv2D: {encoded_conv2d}")
print(f"Decodificación Conv2D: {decoded_conv2d}")

encoded_dropout = encode_layer_params(3, 1)  # Dropout con tasa de 0.3
decoded_dropout = decode_layer_params(encoded_dropout)
print(f"\nCodificación real de Dropout: {encoded_dropout}")
print(f"Decodificación Dropout: {decoded_dropout}")

encoded_dense = encode_layer_params(4, 128, 0)  # Dense con 128 neuronas y activación ReLU
decoded_dense = decode_layer_params(encoded_dense)
print(f"\nCodificación real de Dense: {encoded_dense}")
print(f"Decodificación Dense: {decoded_dense}")

encoded_repetition = encode_layer_params(8, 3, 5)  # Repetition para repetir las últimas 3 capas 5 veces
decoded_repetition = decode_layer_params(encoded_repetition)
print(f"\nCodificación real de Repetition: {encoded_repetition}")
print(f"Decodificación Repetition: {decoded_repetition}")

x = [1, 0, 0, 0, 6, 5, 0, 2, 8, 1, 1, 0, 4, 17, 3, 0, 4, 22, 0, 0, 7, 0, 0, 0, 0, 11, 1, 3, 3, 0, 0, 0, 3, 1, 0, 0, 4, 63, 3, 0, 1, 0, 0, 0, 5, 0, 0, 0]
print(x)
y = convert_individual(x)
print(y)
z = convert_individual(y, to_real=False)
print(z)
print(x == z)

import tensorflow as tf

# Clase para capas neutrales 'DontCare'
class DontCareLayer(tf.keras.layers.Layer):
    def __init__(self):
        super(DontCareLayer, self).__init__()

    def call(self, inputs):
        return inputs

import random

def fixArch(encoded_model, verbose=False):
    """
    Corrige la arquitectura codificada del modelo, asegurando que:
    - Se evite la presencia de capas incompatibles después de una capa Dense.
    - En caso de una capa de Repetition, se ajuste el alcance de repetición si no hay suficientes capas anteriores.
    - Limita la arquitectura a una sola capa de SelfAttention.

    Parameters:
        encoded_model (list): Lista codificada de la arquitectura del modelo.
        verbose (bool): Si es True, muestra las correcciones realizadas.

    Returns:
        list: Lista con la arquitectura corregida, truncada a un máximo de 48 alelos.
    """

    fixed_layers = []         # Lista que almacenará la arquitectura corregida
    input_is_flattened = False # Indicador para saber si ya hay una capa Flatten en el modelo
    dense_started = False      # Indicador para saber si ya se ha encontrado una capa Dense
    index = 0                  # Índice para recorrer el modelo codificado
    found_self_attention = False  # Flag para rastrear la primera aparición de SelfAttention

    while index < len(encoded_model) and len(fixed_layers) < 48:
        layer_type = int(encoded_model[index])  # Obtener el tipo de capa actual

        # Si ya se ha procesado una capa Dense, sólo se permiten Dense, BatchNorm o DontCare
        if dense_started and layer_type not in [4, 1, 7]:
            if verbose:
                print(f"Se encontró una capa de tipo {layer_type} después de una Dense, reemplazando con DontCare")
            fixed_layers.extend([7, 0, 0, 0])
            index += 4
            continue

        # Procesar la capa de Repetition
        if layer_type == 8:
            repetition_layers = int(encoded_model[index + 1])
            repetition_count = min(max(int(encoded_model[index + 2]), 0), 32)
            actual_layers_to_repeat = min(repetition_layers, len(fixed_layers) // 4)
            if actual_layers_to_repeat != repetition_layers:
                if verbose:
                    print(f"Ajustando alcance de repetición de {repetition_layers} a {actual_layers_to_repeat} debido a falta de capas.")
                repetition_layers = actual_layers_to_repeat
            fixed_layers.extend([layer_type, repetition_layers, repetition_count, 0])
            index += 4
            continue

        # Procesar cada tipo de capa normal
        if layer_type == 0:  # Conv2D
            if input_is_flattened:
                fixed_layers.extend([7, 0, 0, 0])  # DontCare
            else:
                filters = min(max(int(encoded_model[index + 1]), 4), 32)
                stride_idx = min(max(int(encoded_model[index + 2]), 0), 1)
                activation_idx = min(max(int(encoded_model[index + 3]), 0), 3)
                fixed_layers.extend([layer_type, filters, stride_idx, activation_idx])

        elif layer_type == 6:  # SelfAttention
            if input_is_flattened or found_self_attention:
                fixed_layers.extend([7, 0, 0, 0])
                if verbose and found_self_attention:
                    print("Capa SelfAttention adicional reemplazada con DontCare.")
            else:
                filters = min(max(int(encoded_model[index + 1]), 4), 64)
                attention_heads = min(max(int(encoded_model[index + 2]), 1), 4)
                activation_idx = min(max(int(encoded_model[index + 3]), 0), 3)
                # Ajustar filters para que sea divisible por attention_heads:
                if filters % attention_heads != 0:
                    nuevo_valor = filters - (filters % attention_heads)
                    if verbose:
                        print(f"Warning: SelfAttention filters {filters} no es divisible por attention_heads {attention_heads}. Ajustando filters a {nuevo_valor}")
                    filters = nuevo_valor if nuevo_valor >= 4 else 4  # Asegurarse de que no sea menor que 4
                fixed_layers.extend([layer_type, filters, attention_heads, activation_idx])
                found_self_attention = True

        elif layer_type == 2:  # MaxPooling
            if input_is_flattened:
                fixed_layers.extend([7, 0, 0, 0])
            else:
                stride_idx = min(max(int(encoded_model[index + 1]), 0), 1)
                fixed_layers.extend([layer_type, stride_idx, 0, 0])

        elif layer_type == 3:  # Dropout
            rate_idx = min(max(int(encoded_model[index + 1]), 0), 3)
            fixed_layers.extend([layer_type, rate_idx, 0, 0])

        elif layer_type == 4:  # Dense
            neurons = min(max(int(encoded_model[index + 1]), 1), 512)
            activation_idx = min(max(int(encoded_model[index + 2]), 0), 3)
            fixed_layers.extend([layer_type, neurons, activation_idx, 0])
            dense_started = True  # Marcar que ya se encontró una capa Dense

        elif layer_type == 1:  # BatchNorm
            if len(fixed_layers) > 0:
                prev_layer = fixed_layers[-4:]
                prev_layer_type = prev_layer[0]
                if prev_layer_type in [0, 6]:
                    num_features = prev_layer[1]
                else:
                    num_features = 4
            else:
                num_features = 4
            if verbose:
                print(f"📌 Configurando BatchNorm con {num_features} canales")
            fixed_layers.extend([layer_type, num_features, 0, 0])

        elif layer_type == 5:  # Flatten
            if input_is_flattened or dense_started:
                fixed_layers.extend([7, 0, 0, 0])
            else:
                if index + 4 < len(encoded_model):
                    next_layer_type = int(encoded_model[index + 4])
                    if next_layer_type not in [4, 7]:  # Flatten debería ir seguido de Dense o DontCare
                        if verbose:
                            print(f"⚠️ WARNING: Flatten seguido de {next_layer_type}, reemplazando con DontCare")
                        fixed_layers.extend([7, 0, 0, 0])
                    else:
                        fixed_layers.extend([layer_type, 0, 0, 0])
                        input_is_flattened = True
                else:
                    fixed_layers.extend([layer_type, 0, 0, 0])
                    input_is_flattened = True

        elif layer_type == 7:  # DontCare
            fixed_layers.extend([layer_type, 0, 0, 0])

        else:  # Cualquier otro tipo
            fixed_layers.extend([7, 0, 0, 0])

        index += 4

    return fixed_layers[:48]

def encode_model_architecture(model_dict, max_alleles=48):
    """
    Codifica la arquitectura del modelo en una lista de valores con un máximo de `max_alleles`.
    Cada capa se codifica en función de sus parámetros.
    """
    encoded_layers = []
    total_alleles = 0

    for layer in model_dict['layers']:
        # Initialize encoded_layer here to a default value
        encoded_layer = []  # or any other suitable default

        if layer['type'] == 'Repetition':  # Codificar capa de repetición
            encoded_layer = encode_layer_params(
                layer_type_idx=8,  # índice para 'Repetition'
                param1=layer.get('repetition_layers', 0),
                param2=layer.get('repetition_count', 1)
            )
        else:
            # ... (rest of your code remains the same) ...
            # Get layer_type_idx, defaulting to 'DontCare' if not found
            layer_type_idx = next(
                (key for key, value in layer_type_options.items() if value == layer['type']),
                layer_type_options[7] # Default to 'DontCare' if not found
            )

            # Codificar parámetros específicos de cada tipo de capa
            if layer['type'] == 'Conv2D':
                param1 = max(4, min(layer.get('filters', 8), 32))  # Limitar filtros dentro del rango [4, 32]
                param2 = next((key for key, value in stride_options.items() if value == layer.get('strides', 1.0)), 0)
                param3 = next((key for key, value in activation_options.items() if value == layer.get('activation', 'relu')), 0)
                encoded_layer = [layer_type_idx, param1, param2, param3]

            elif layer['type'] == 'SelfAttention':  # Reemplazo de DepthwiseConv2D por SelfAttention
                param1 = max(4, min(layer.get('filters', 8), 64))  # Limitar filtros dentro del rango [4, 64]
                param2 = max(1, min(layer.get('attention_heads', 1), 8))  # Número de cabezas de atención [1, 8]
                param3 = next((key for key, value in activation_options.items() if value == layer.get('activation', 'relu')), 0)
                encoded_layer = [layer_type_idx, param1, param2, param3]

            elif layer['type'] == 'Dense':
                param1 = max(1, min(layer.get('units', 1), 512))  # Limitar neuronas dentro del rango [1, 512]
                param2 = next((key for key, value in activation_options.items() if value == layer.get('activation', 'relu')), 0)
                encoded_layer = [layer_type_idx, param1, param2, 0]

            elif layer['type'] == 'MaxPooling':
                param1 = next((key for key, value in stride_options.items() if value == layer.get('strides', 1.0)), 0)
                encoded_layer = [layer_type_idx, param1, 0, 0]

            elif layer['type'] == 'Dropout':
                param1 = next((key for key, value in dropout_options.items() if value == layer.get('rate', 0.2)), 0)
                encoded_layer = [layer_type_idx, param1, 0, 0]

            elif layer['type'] == 'BatchNorm':
                encoded_layer = [layer_type_idx, 0, 0, 0]

            elif layer['type'] == 'Flatten':
                encoded_layer = [layer_type_idx, 0, 0, 0]

            elif layer['type'] == 'DontCare':
                encoded_layer = [layer_type_idx, 0, 0, 0]

        # Añadir la codificación de la capa a la lista de alelos
        encoded_layers.extend(encoded_layer)
        total_alleles += len(encoded_layer)

    # Rellenar con 'DontCare' si el total de alelos es menor que `max_alleles`
    while total_alleles < max_alleles:
        dont_care_encoding = encode_layer_params(7)  # índice de 'DontCare'
        encoded_layers.extend(dont_care_encoding)
        total_alleles += len(dont_care_encoding)

    # Recortar si excede `max_alleles`
    final_encoding = encoded_layers[:max_alleles]

    return final_encoding

def decode_model_architecture(encoded_model):
    """
    Decodifica la arquitectura del modelo a partir de la lista codificada de valores (índices),
    aplicando las reglas de repetición y asegurando la inclusión de una capa convolucional inicial.
    """
    model_dict = {'layers': []}  # Lista de capas decodificadas
    index = 0
    found_self_attention = False  # Flag para asegurar una sola SelfAttention

    while index < len(encoded_model):
        layer_type = int(encoded_model[index])
        param1 = encoded_model[index + 1]
        param2 = encoded_model[index + 2]
        param3 = encoded_model[index + 3]

        if layer_type == 8:  # Capa de Repetition
            repetition_layers = int(param1)
            repetition_count = int(param2)

            # Selecciona solo capas válidas para la repetición (sin incluir SelfAttention)
            layers_to_repeat = select_group_for_repetition(model_dict['layers'], repetition_layers)

            if len(layers_to_repeat) > 0:
                for _ in range(repetition_count):
                    for layer in layers_to_repeat:
                        # Si la capa es SelfAttention, reemplazarla con DontCare
                        if layer['type'] == 'SelfAttention':
                            model_dict['layers'].append({'type': 'DontCare'})
                        else:
                            model_dict['layers'].append(layer)

        else:
            decoded_layer = {}

            if layer_type == 0:  # Conv2D
                decoded_layer = {
                    'type': 'Conv2D',
                    'filters': max(4, min(param1, 32)),  # Limita `filters` entre 4 y 32
                    'strides': stride_options.get(param2, 1),
                    'activation': activation_options.get(param3, 'relu')
                }
            elif layer_type == 6:  # SelfAttention
                if found_self_attention:  # Si ya hay una SelfAttention, la ignoramos
                    index += 4
                    continue
                decoded_layer = {
                    'type': 'SelfAttention',
                    'filters': max(4, min(param1, 64)),  # Limita `filters` entre 4 y 64
                    'attention_heads': max(1, min(param2, 4)),  # Limita `attention_heads` entre 1 y 4
                    'activation': activation_options.get(param3, 'relu')
                }
                found_self_attention = True  # Marca que ya se agregó una SelfAttention
            elif layer_type == 2:  # MaxPooling
                decoded_layer = {
                    'type': 'MaxPooling',
                    'strides': stride_options.get(param1, 1)
                }
            elif layer_type == 3:  # Dropout
                decoded_layer = {
                    'type': 'Dropout',
                    'rate': dropout_options.get(param1, 0.2)
                }
            elif layer_type == 4:  # Dense
                decoded_layer = {
                    'type': 'Dense',
                    'units': max(1, min(param1, 512)),  # Limita `units` entre 1 y 512
                    'activation': activation_options.get(param2, 'relu')
                }
            elif layer_type == 1:  # BatchNorm
                decoded_layer = {'type': 'BatchNorm'}
            elif layer_type == 5:  # Flatten
                decoded_layer = {'type': 'Flatten'}
            elif layer_type == 7:  # DontCare
                decoded_layer = {'type': 'DontCare'}

            model_dict['layers'].append(decoded_layer)

        index += 4

    # Asegura que haya una capa Flatten antes de la capa Dense final, si no ya existe una Flatten
    if model_dict['layers'][-1]['type'] != 'Flatten':
        model_dict['layers'].append({'type': 'Flatten'})

    # Añade la capa Dense final obligatoria
    model_dict['layers'].append({'type': 'Dense', 'units': 1, 'activation': 'sigmoid'})

    return model_dict

def select_group_for_repetition(layers, repetition_layers):
    """
    Selecciona el primer grupo válido para repetición en función de las reglas de compatibilidad,
    evitando la duplicación de SelfAttention.

    Parameters:
        layers (list): Lista de capas ya procesadas, donde cada capa es un diccionario.
        repetition_layers (int): Número de capas hacia atrás para considerar en la repetición.

    Returns:
        list: Lista de capas compatibles para repetición, sin SelfAttention.
    """
    valid_layers = []
    group_type = None

    # Retrocede desde el final de `layers` para encontrar el grupo válido
    for layer in reversed(layers[-repetition_layers:]):
        if group_type is None:
            # Determina el tipo de grupo
            if layer['type'] in ['Flatten', 'Dense']:
                group_type = 'dense'
                valid_layers.insert(0, layer)
            elif layer['type'] in ['Conv2D', 'SelfAttention', 'MaxPooling']:
                group_type = 'convolutional'
                valid_layers.insert(0, layer)
            elif layer['type'] in ['BatchNorm', 'DontCare']:  # BatchNorm y DontCare son compatibles con ambos grupos
                valid_layers.insert(0, layer)
        else:
            # Agrega solo capas compatibles con el grupo seleccionado
            if group_type == 'dense' and layer['type'] in ['Dense', 'Flatten', 'BatchNorm', 'Dropout', 'DontCare']:
                valid_layers.insert(0, layer)
            elif group_type == 'convolutional' and layer['type'] in ['Conv2D', 'MaxPooling', 'BatchNorm', 'Dropout', 'DontCare']:
                valid_layers.insert(0, layer)

    return valid_layers

import tensorflow as tf



def self_attention_block(x, filters, window_size=8, attention_heads=4, verbose=False):
    # Ajuste rápido de filters
    if filters % attention_heads != 0:
        filters = filters - (filters % attention_heads)
        filters = max(filters, attention_heads)
    d_head = filters // attention_heads

    # Dimensiones dinámicas
    B = tf.shape(x)[0]
    H = tf.shape(x)[1]
    W = tf.shape(x)[2]
    C = tf.shape(x)[3]

    # Ventana
    ws = tf.minimum(tf.minimum(window_size, H), W)
    ws = tf.cast(ws, tf.int32)

    # Padding necesario
    pad_h = (ws - H % ws) % ws
    pad_w = (ws - W % ws) % ws

    # Funciones para tf.cond
    def _do_pad():
        return tf.pad(x, [[0,0],[0,pad_h],[0,pad_w],[0,0]])
    def _no_pad():
        return x

    x_padded = tf.cond(
        tf.logical_or(tf.greater(pad_h, 0), tf.greater(pad_w, 0)),
        _do_pad, _no_pad
    )

    H_pad = tf.shape(x_padded)[1]
    W_pad = tf.shape(x_padded)[2]
    num_h = H_pad // ws
    num_w = W_pad // ws

    # Particionar en ventanas
    windows = tf.reshape(x_padded, [B, num_h, ws, num_w, ws, C])
    windows = tf.transpose(windows, [0,1,3,2,4,5])
    windows = tf.reshape(windows, [-1, ws, ws, C])

    # QKV por conv 1x1
    Q = tf.keras.layers.Conv2D(filters,1,padding='same')(windows)
    K_mat = tf.keras.layers.Conv2D(filters,1,padding='same')(windows)
    V = tf.keras.layers.Conv2D(filters,1,padding='same')(windows)

    N = ws*ws
    def _reshape(t):
        return tf.reshape(t, [-1, N, filters])
    Q = _reshape(Q); K_mat = _reshape(K_mat); V = _reshape(V)

    # split heads
    def split_heads(t):
        t = tf.reshape(t, [-1, N, attention_heads, d_head])
        return tf.transpose(t, [0,2,1,3])
    Q = split_heads(Q); K_mat = split_heads(K_mat); V = split_heads(V)

    # atención escalada
    scale = tf.math.rsqrt(tf.cast(d_head, tf.float32))
    scores = tf.matmul(Q, K_mat, transpose_b=True) * scale
    weights = tf.nn.softmax(scores, axis=-1)
    out = tf.matmul(weights, V)

    # fuse heads
    out = tf.transpose(out, [0,2,1,3])
    out = tf.reshape(out, [-1, N, filters])
    out = tf.reshape(out, [-1, ws, ws, filters])

    # reconstrucción
    out = tf.reshape(out, [B, num_h, num_w, ws, ws, filters])
    out = tf.transpose(out, [0,1,3,2,4,5])
    out = tf.reshape(out, [B, H_pad, W_pad, filters])

    # Funciones de recorte
    def _do_crop():
        return out[:, :H, :W, :]
    def _no_crop():
        return out

    out_final = tf.cond(
        tf.logical_or(tf.greater(pad_h, 0), tf.greater(pad_w, 0)),
        _do_crop, _no_crop
    )
    return out_final

def build_tf_model_from_dict_simple(model_dict, input_shape=(128,128,3), verbose=False):
    inp = tf.keras.Input(shape=input_shape)
    x = inp

    # forzar 4 canales como antes
    if input_shape[-1] != 4:
        x = tf.keras.layers.Conv2D(4,1,padding='same')(x)

    for layer in model_dict['layers']:
        t = layer['type']
        if t == 'Conv2D':
            x = tf.keras.layers.Conv2D(layer['filters'],3,
                                       strides=layer['strides'],
                                       padding='same')(x)
            act = layer['activation'].lower()
            x = (tf.keras.layers.ReLU() if act=='relu' else tf.keras.layers.LeakyReLU())(x)

        elif t == 'DepthwiseConv2D':
            x = tf.keras.layers.DepthwiseConv2D(3,
                                                strides=layer['strides'],
                                                padding='same')(x)
            x = tf.keras.layers.Activation(layer['activation'])(x)

        elif t == 'BatchNorm':
            x = tf.keras.layers.BatchNormalization()(x)

        elif t == 'MaxPooling':
            x = tf.keras.layers.MaxPooling2D(2,
                                             strides=layer['strides'],
                                             padding='same')(x)

        elif t == 'Flatten':
            x = tf.keras.layers.Flatten()(x)

        elif t == 'Dense':
            x = tf.keras.layers.Dense(layer['units'],
                                      activation=layer['activation'])(x)

        elif t == 'Dropout':
            x = tf.keras.layers.Dropout(layer['rate'])(x)

        elif t == 'DontCare':
            x = tf.identity(x)

        elif t == 'SelfAttention':
            filt = layer['filters']
            if x.shape[-1] != filt:
                x = tf.keras.layers.Conv2D(filt,1,padding='same')(x)
            ws = layer.get('window_size',16)
            heads = layer.get('attention_heads',4)
            x = tf.keras.layers.Lambda(
                lambda zz: self_attention_block(zz, filters=filt,
                                                window_size=ws,
                                                attention_heads=heads,
                                                verbose=verbose),
                output_shape=lambda s: (s[0], s[1], s[2], filt)
            )(x)
        else:
            if verbose:
                print("Omitiendo tipo desconocido:", t)

    return tf.keras.Model(inputs=inp, outputs=x)

# Ejemplo
if __name__=="__main__":
    model_dict = {
        "layers":[
            {"type":"Conv2D","filters":32,"strides":1,"activation":"relu"},
            {"type":"BatchNorm"},
            {"type":"MaxPooling","strides":2},
            {"type":"SelfAttention","filters":32,"window_size":8,"attention_heads":4},
            {"type":"Flatten"},
            {"type":"Dense","units":10,"activation":"softmax"}
        ]
    }
    m = build_tf_model_from_dict_simple(model_dict, input_shape=(128,128,3), verbose=True)
    m.summary()


def build_tf_model_from_dict(model_dict, input_shape=(128, 128, 3), verbose=False):
    """
    Construye un modelo de TensorFlow a partir de un diccionario de arquitectura, sin usar clases personalizadas.

    Tipos de capas soportadas:
      - 'Conv2D', 'DepthwiseConv2D', 'BatchNorm', 'MaxPooling',
        'Flatten', 'Dense', 'Dropout', 'DontCare', 'SelfAttention'

    Args:
        model_dict: diccionario con la definición de capas.
        input_shape: forma de la entrada (altura, anchura, canales).
        verbose: si True, muestra mensajes de depuración.

    Retorna:
        Un objeto tf.keras.Model.
    """
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs

    # Conversión de canales si es necesario: si la entrada no tiene 4 canales, se ajusta.
    target_in_channels = 4
    if input_shape[-1] != target_in_channels:
        if verbose:
            print(f"Insertando capa de conversión: de {input_shape[-1]} a {target_in_channels} canales.")
        x = tf.keras.layers.Conv2D(target_in_channels, kernel_size=1, padding='same')(x)

    # Recorrer las capas del diccionario
    for layer in model_dict['layers']:
        if layer['type'] == 'Conv2D':
            x = tf.keras.layers.Conv2D(filters=layer['filters'],
                                       kernel_size=3,
                                       strides=layer['strides'],
                                       padding='same')(x)
            if layer['activation'].lower() == "relu":
                x = tf.keras.layers.ReLU()(x)
            else:
                x = tf.keras.layers.LeakyReLU()(x)

        elif layer['type'] == 'DepthwiseConv2D':
            x = tf.keras.layers.DepthwiseConv2D(kernel_size=3,
                                                strides=layer['strides'],
                                                padding='same')(x)
            x = tf.keras.layers.Activation(layer['activation'])(x)

        elif layer['type'] == 'BatchNorm':
            x = tf.keras.layers.BatchNormalization()(x)

        elif layer['type'] == 'MaxPooling':
            x = tf.keras.layers.MaxPooling2D(pool_size=2,
                                             strides=layer['strides'],
                                             padding='same')(x)

        elif layer['type'] == 'Flatten':
            x = tf.keras.layers.Flatten()(x)

        elif layer['type'] == 'Dense':
            x = tf.keras.layers.Dense(units=layer['units'],
                                      activation=layer['activation'])(x)

        elif layer['type'] == 'Dropout':
            x = tf.keras.layers.Dropout(rate=layer['rate'])(x)

        elif layer['type'] == 'DontCare':
            x = tf.identity(x)

        elif layer['type'] == 'SelfAttention':
            desired_filters = layer['filters']
            # Ajustar canales si es necesario.
            if x.shape[-1] != desired_filters:
                if verbose:
                    print(f"Ajustando canales en SelfAttention: {x.shape[-1]} -> {desired_filters}")
                x = tf.keras.layers.Conv2D(filters=desired_filters,
                                           kernel_size=1,
                                           padding='same')(x)
            window_size = layer.get('window_size', 16)
            attention_heads = layer.get('attention_heads', 4)
            # Uso de Lambda con argumento output_shape para evitar el error.
            x = tf.keras.layers.Lambda(
                lambda t: self_attention_block(t, filters=desired_filters,
                                               window_size=window_size,
                                               attention_heads=attention_heads,
                                               verbose=verbose),
                output_shape=lambda s: (s[0], s[1], s[2], desired_filters)
            )(x)
        else:
            if verbose:
                print(f"Tipo de capa desconocido: {layer['type']}. Se omite.")

    model = tf.keras.Model(inputs=inputs, outputs=x)
    return model

# Ejemplo de uso:
if __name__ == "__main__":
    model_dict = {
        "layers": [
            {"type": "Conv2D", "filters": 32, "strides": 1, "activation": "relu"},
            {"type": "BatchNorm"},
            {"type": "MaxPooling", "strides": 2},
            {"type": "SelfAttention", "filters": 32, "window_size": 8, "attention_heads": 4, "activation": "relu"},
            {"type": "Flatten"},
            {"type": "Dense", "units": 10, "activation": "softmax"}
        ]
    }

    model = build_tf_model_from_dict_simple(model_dict, input_shape=(128, 128, 3), verbose=True)
    model.summary()

import random
import tensorflow as tf

def generate_random_architecture():
    num_layers = 12
    layers = []

    for _ in range(num_layers):
        layer_type = random.choice([
            'Conv2D', 'DepthwiseConv2D', 'BatchNorm', 'MaxPooling', 'Dropout',
            'Dense', 'Flatten', 'DontCare', 'Repetition'
        ])
        layers.append(generate_layer(layer_type))
    return {"layers": layers}

def generate_layer(layer_type):
    if layer_type == 'Conv2D':
        return {
            "type": "Conv2D",
            "filters": random.randint(4, 16),  # Rango reducido para filtros
            "strides": random.choice([1, 2]),
            "activation": random.choice(["relu", "leaky_relu", "sigmoid", "tanh"])
        }
    elif layer_type == 'DepthwiseConv2D':
        return {
            "type": "DepthwiseConv2D",
            "filters": random.randint(4, 16),  # Rango reducido para filtros
            "strides": random.choice([1, 2]),
            "activation": random.choice(["relu", "leaky_relu", "sigmoid", "tanh"])
        }
    elif layer_type == 'BatchNorm':
        return {"type": "BatchNorm"}
    elif layer_type == 'MaxPooling':
        return {
            "type": "MaxPooling",
            "strides": random.choice([1, 2])
        }
    elif layer_type == 'Dropout':
        return {
            "type": "Dropout",
            "rate": random.choice([0.2, 0.3, 0.4, 0.5])
        }
    elif layer_type == 'Dense':
        return {
            "type": "Dense",
            "units": random.randint(1, 128),  # Rango reducido para unidades
            "activation": random.choice(["relu", "leaky_relu", "sigmoid", "tanh"])
        }
    elif layer_type == 'Flatten':
        return {"type": "Flatten"}
    elif layer_type == 'DontCare':
        return {"type": "DontCare"}
    elif layer_type == 'Repetition':
        return {
            "type": "Repetition",
            "repetition_layers": random.randint(1, 3),  # Limitar el número de capas para repetir
            "repetition_count": random.randint(1, 2)  # Limitar el conteo de repeticiones
        }
    return {}

import numpy as np

def get_succ_m(parents, children):
  # Count if mutation was successful than the average parent fitness
  parent_fitness = [parent['fitness'] for parent in parents]
  avg_fitness = np.mean(parent_fitness)

  succ_m_count = sum(1 for child in children if child['fitness'] < avg_fitness)

  return succ_m_count

def get_cr_points(rp, n):
  indexes = list(range(n))
  j_star = random.sample(indexes, n // 2)

  for j in range(n):
    if random.random() < rp and j not in j_star:
      j_star.append(j)

  return j_star

def map_to_architecture_params(latin_hypercube_sample):
    """
    Mapea una muestra del hipercubo latino a parámetros de arquitectura de red neuronal.

    Args:
        latin_hypercube_sample: Muestra del hipercubo latino (valores entre 0 y 1)

    Returns:
        Diccionario con la arquitectura de la red neuronal
    """

    # Asumimos que la muestra tiene dimensiones múltiplo de 3 (tipo, param1, param2)
    num_layers = len(latin_hypercube_sample) // 3

    # Mapear tipo de capa (9 tipos posibles)
    layer_type_idx = int(latin_hypercube_sample[0] * 9)
    layer_mapping = ['Conv2D', 'SelfAttention', 'BatchNorm', 'MaxPooling',
                     'Dropout', 'Dense', 'Flatten', 'DontCare', 'Repetition']

    if layer_type_idx >= len(layer_mapping):
        layer_type = 'DontCare'
    else:
        layer_type = layer_mapping[layer_type_idx]

    # Crear diccionario de capa según su tipo
    layer_dict = {'type': layer_type}

    if layer_type == 'Conv2D':
        layer_dict['filters'] = int(latin_hypercube_sample[1] * (32 - 4) + 4)  # [4, 32]
        stride_idx = int(latin_hypercube_sample[2] * 2)  # [0, 1]
        layer_dict['strides'] = stride_options.get(stride_idx, 1)
        layer_dict['activation'] = 'relu'  # Default

    elif layer_type == 'SelfAttention':
        layer_dict['filters'] = int(latin_hypercube_sample[1] * (64 - 4) + 4)  # [4, 64]
        layer_dict['attention_heads'] = int(latin_hypercube_sample[2] * (8 - 1) + 1)  # [1, 8]
        layer_dict['activation'] = 'relu'  # Default

    elif layer_type == 'MaxPooling':
        stride_idx = int(latin_hypercube_sample[1] * 2)  # [0, 1]
        layer_dict['strides'] = stride_options.get(stride_idx, 1)

    elif layer_type == 'Dropout':
        rate_idx = int(latin_hypercube_sample[1] * 4)  # [0, 3]
        layer_dict['rate'] = dropout_options.get(rate_idx, 0.2)

    elif layer_type == 'Dense':
        layer_dict['units'] = int(latin_hypercube_sample[1] * (512 - 1) + 1)  # [1, 512]
        layer_dict['activation'] = 'relu'  # Default

    return layer_dict # Return a single layer dictionary

def pop_gen(num_models):
  archs = []
  for i in range(num_models):
        random_architecture = encode_model_architecture(generate_random_architecture())
        repaired_architecture_str = fixArch(random_architecture)
        archs.append({'individual': repaired_architecture_str, 'fitness': 0})
  return archs

def pop_gen(num_models, max_alleles=48):
    """
    Genera una población inicial utilizando el hipercubo latino y las funciones existentes.

    Args:
        num_models: int - Número de individuos a generar.
        max_alleles: int - Número máximo de alelos en los cromosomas.

    Returns:
        list - Lista de diccionarios con individuos y su fitness inicializado a 0.
    """
    # Padres iniciales predefinidos (arquitecturas base)
    initial_parents = [
        [0, 30, 0, 0, 3, 0, 0, 0, 2, 1, 0, 0, 0, 16, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 16, 0, 0, 3, 0, 0, 0, 5, 0, 0, 0, 4, 256, 0, 0, 3, 1, 0, 0],
        [1, 0, 0, 0, 0, 16, 0, 1, 1, 0, 0, 0, 0, 8, 0, 1, 1, 0, 0, 0, 5, 0, 0, 0, 4, 32, 1, 0, 4, 1, 2, 0, 7, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0],
        [0, 32, 0, 1, 1, 0, 0, 0, 2, 1, 0, 0, 8, 3, 31, 0, 5, 0, 0, 0, 4, 256, 0, 0, 3, 3, 0, 0, 4, 1, 2, 0, 7, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0]
    ]

    # Añadir arquitecturas base a la población
    population = [{'individual': fixArch(parent)} for parent in initial_parents]

    # Número de modelos aleatorios a generar
    num_random = num_models - len(initial_parents)

    if num_random <= 0:
        return population

    # Dimensiones para el hipercubo latino (12 capas x 3 parámetros por capa)
    dimensions = 12 * 3

    # Generar muestras del hipercubo latino
    latin_samples = generate_latin_hypercube_samples(num_random, dimensions)

    # Conjunto para almacenar arquitecturas únicas (como tuplas para poder usar set)
    unique_architectures = set(tuple(convert_individual(p['individual'], to_real=False)) for p in population)

    # Contador de intentos para evitar bucles infinitos
    max_attempts = 100

    for sample in latin_samples:
        # Transformar cada muestra en una arquitectura
        model_samples = np.array(sample).reshape(12, 3)
        model_dict = {
            "layers": [map_to_architecture_params(layer_sample) for layer_sample in model_samples]
        }

        # Codificar el modelo y repararlo
        encoded_chromosome = encode_model_architecture(model_dict, max_alleles=max_alleles)
        repaired_architecture = fixArch(encoded_chromosome)

        # Verificar si esta arquitectura ya existe en la población
        arch_tuple = tuple(convert_individual(repaired_architecture, to_real=False))

        attempts = 0
        while arch_tuple in unique_architectures and attempts < max_attempts:
            # Si ya existe, aplicar una pequeña perturbación
            perturbed_architecture = perturb_architecture(repaired_architecture)
            repaired_architecture = fixArch(perturbed_architecture)
            arch_tuple = tuple(convert_individual(repaired_architecture, to_real=False))
            attempts += 1

        if attempts < max_attempts:  # Solo añadir si encontramos una arquitectura única
            unique_architectures.add(arch_tuple)
            population.append({"individual": repaired_architecture})

    # Si no tenemos suficientes modelos, generar más hasta alcanzar num_models
    while len(population) < num_models:
        # Generar una nueva muestra aleatoria
        random_sample = np.random.random(dimensions)
        model_samples = random_sample.reshape(12, 3)
        model_dict = {
            "layers": [map_to_architecture_params(layer_sample) for layer_sample in model_samples]
        }

        encoded_chromosome = encode_model_architecture(model_dict, max_alleles=max_alleles)
        repaired_architecture = fixArch(encoded_chromosome)

        # Verificar si esta arquitectura ya existe
        arch_tuple = tuple(convert_individual(repaired_architecture, to_real=False))
        if arch_tuple not in unique_architectures:
            unique_architectures.add(arch_tuple)
            population.append({"individual": repaired_architecture})

    return population

def perturb_architecture(architecture, perturbation_rate=0.2):
    """
    Aplica una pequeña perturbación a una arquitectura para generar variación.

    Args:
        architecture: list - Arquitectura codificada a perturbar.
        perturbation_rate: float - Tasa de perturbación (probabilidad de modificar cada alelo).

    Returns:
        list - Arquitectura perturbada.
    """
    perturbed = architecture.copy()

    for i in range(0, len(perturbed), 4):
        # No perturbamos el tipo de capa para mantener la estructura general
        # Solo perturbamos los parámetros de la capa

        layer_type = perturbed[i]

        # Perturbación para Conv2D
        if layer_type == 0 and i+3 < len(perturbed):
            if np.random.random() < perturbation_rate:
                # Perturbar filtros (entre 4 y 32)
                perturbed[i+1] = max(4, min(perturbed[i+1] + np.random.randint(-4, 5), 32))
            if np.random.random() < perturbation_rate:
                # Perturbar stride (0 o 1)
                perturbed[i+2] = 1 if perturbed[i+2] == 0 else 0
            if np.random.random() < perturbation_rate:
                # Perturbar activación (0-3)
                perturbed[i+3] = np.random.randint(0, 4)

        # Perturbación para SelfAttention
        elif layer_type == 6 and i+3 < len(perturbed):
            if np.random.random() < perturbation_rate:
                # Perturbar filtros (entre 4 y 64)
                perturbed[i+1] = max(4, min(perturbed[i+1] + np.random.randint(-8, 9), 64))
            if np.random.random() < perturbation_rate:
                # Perturbar attention_heads (entre 1 y 8)
                perturbed[i+2] = max(1, min(perturbed[i+2] + np.random.randint(-2, 3), 8))
            if np.random.random() < perturbation_rate:
                # Perturbar activación (0-3)
                perturbed[i+3] = np.random.randint(0, 4)

        # Perturbación para MaxPooling
        elif layer_type == 2 and i+1 < len(perturbed):
            if np.random.random() < perturbation_rate:
                # Perturbar stride (0 o 1)
                perturbed[i+1] = 1 if perturbed[i+1] == 0 else 0

        # Perturbación para Dropout
        elif layer_type == 3 and i+1 < len(perturbed):
            if np.random.random() < perturbation_rate:
                # Perturbar rate (0-3)
                perturbed[i+1] = np.random.randint(0, 4)

        # Perturbación para Dense
        elif layer_type == 4 and i+2 < len(perturbed):
            if np.random.random() < perturbation_rate:
                # Perturbar unidades (entre 1 y 512)
                perturbed[i+1] = max(1, min(perturbed[i+1] + np.random.randint(-32, 33), 512))
            if np.random.random() < perturbation_rate:
                # Perturbar activación (0-3)
                perturbed[i+2] = np.random.randint(0, 4)

        # Perturbación para Repetition
        elif layer_type == 8 and i+2 < len(perturbed):
            if np.random.random() < perturbation_rate:
                # Perturbar capas a repetir (entre 1 y 4)
                perturbed[i+1] = max(1, min(perturbed[i+1] + np.random.randint(-1, 2), 4))
            if np.random.random() < perturbation_rate:
                # Perturbar número de repeticiones (entre 1 y 32)
                perturbed[i+2] = max(1, min(perturbed[i+2] + np.random.randint(-2, 3), 32))

    return perturbed

def generate_latin_hypercube_samples(num_samples, dimensions):
    """
    Genera muestras usando Latin Hypercube Sampling y las convierte a valores enteros
    adecuados para la codificación de arquitecturas de redes neuronales.

    Args:
        num_samples: Número de muestras a generar
        dimensions: Número de dimensiones (alelos) para cada muestra

    Returns:
        Lista de arquitecturas codificadas como listas de enteros
    """
    # Generar muestras en el espacio continuo [0,1]
    lhs_samples = lhs(dimensions, samples=num_samples)

    # Convertir las muestras a valores enteros adecuados para la arquitectura
    encoded_samples = []

    for sample in lhs_samples:
        encoded_sample = []

        # Procesar cada grupo de 4 valores (tipo de capa + 3 parámetros)
        for i in range(0, dimensions, 4):
            if i + 3 < dimensions:
                # Convertir el tipo de capa (0-8)
                layer_type = int(sample[i] * 8)  # 9 tipos de capas (0-8)
                encoded_sample.append(layer_type)

                # Procesar parámetros según el tipo de capa
                if layer_type == 0:  # Conv2D
                    filters = int(sample[i+1] * 28) + 4  # Filtros entre [4, 32]
                    stride_idx = int(sample[i+2] * 2)    # Stride 0 o 1
                    activation_idx = int(sample[i+3] * 4) # Activación 0-3
                    encoded_sample.extend([filters, stride_idx, activation_idx])

                elif layer_type == 6:  # SelfAttention
                    filters = int(sample[i+1] * 60) + 4  # Filtros entre [4, 64]
                    attention_heads = int(sample[i+2] * 7) + 1  # Heads entre [1, 8]
                    activation_idx = int(sample[i+3] * 4)  # Activación 0-3
                    encoded_sample.extend([filters, attention_heads, activation_idx])

                elif layer_type == 2:  # MaxPooling
                    stride_idx = int(sample[i+2] * 2)  # Stride 0 o 1
                    encoded_sample.extend([stride_idx, 0, 0])

                elif layer_type == 3:  # Dropout
                    rate_idx = int(sample[i+1] * 4)  # Índice de tasa de dropout 0-3
                    encoded_sample.extend([rate_idx, 0, 0])

                elif layer_type == 4:  # Dense
                    units = int(sample[i+1] * 511) + 1  # Unidades entre [1, 512]
                    activation_idx = int(sample[i+2] * 4)  # Activación 0-3
                    encoded_sample.extend([units, activation_idx, 0])

                elif layer_type == 8:  # Repetition
                    layers_to_repeat = int(sample[i+1] * 3) + 1  # Capas a repetir [1, 4]
                    repetition_count = int(sample[i+2] * 31) + 1  # Número de repeticiones [1, 32]
                    encoded_sample.extend([layers_to_repeat, repetition_count, 0])

                else:  # BatchNorm, Flatten, DontCare
                    encoded_sample.extend([0, 0, 0])
            else:
                # Si no hay suficientes valores para completar un grupo de 4,
                # rellenar con ceros
                remaining = dimensions - i
                encoded_sample.extend([0] * remaining)

        encoded_samples.append(encoded_sample)

    return encoded_samples

import os
import pickle
import glob
import random
from tqdm import tqdm

def es(target_func, mu=10, lamb=1, F=2, rp=0.5, gens=100, n=10, auto_adapt=False, exp=0, resume=False):
    """
    Parámetros:
      - target_func: función objetivo.
      - mu: tamaño de la población.
      - lamb: número de hijos por generación.
      - F: factor de mutación.
      - rp: tasa de recombinación.
      - gens: número total de generaciones.
      - n: ventana para adaptar F (si auto_adapt True).
      - auto_adapt: flag para la adaptación de F.
      - exp: número de experimento (para identificar los checkpoints).
      - resume: bandera que indica si se desea reanudar desde un checkpoint previo.

    La función guarda, cada 100 generaciones, un checkpoint con todo el estado
    del algoritmo en la ruta:
      /content/drive/MyDrive/NAS/surr_m_4_ec/checkpoints/[exp]_[gen].pkl

    Además, al finalizar el experimento se guarda un checkpoint final (exp_final.pkl)
    con los arrays necesarios para graficar.
    """

    # Ruta de la carpeta para guardar los checkpoints en Google Drive
    checkpoint_dir = "/content/drive/MyDrive/NAS/surr_m_4_ec/checkpoints_r2"
    os.makedirs(checkpoint_dir, exist_ok=True)

    # Si se desea reanudar, se busca el último checkpoint para este experimento.
    if resume:
        checkpoint_pattern = os.path.join(checkpoint_dir, f"{exp}_*.pkl")
        checkpoint_files = glob.glob(checkpoint_pattern)
        if checkpoint_files:
            # Se selecciona el checkpoint con la mayor generación
            latest_checkpoint = max(checkpoint_files, key=lambda x: int(x.split('_')[-1].split('.')[0]) if x.split('_')[-1].split('.')[0].isdigit() else -1)
            print("Reanudando desde el checkpoint:", latest_checkpoint)
            with open(latest_checkpoint, "rb") as f:
                state = pickle.load(f)
            start_gen = state.get("current_generation", -1) + 1
            pop = state["population"]
            best_fitness_per_gen = state["best_fitness_per_gen"]
            Fs = state["Fs"]
            F = state["F"]
            succ_m_count = state["succ_m_count"]
        else:
            # Si no se encuentra ningún checkpoint, se inicia el experimento normalmente.
            print("No se encontró checkpoint, iniciando nuevo experimento.")
            start_gen = 0
            pop = pop_gen(mu)
            best_fitness_per_gen = []
            Fs = []
            succ_m_count = 0
    else:
        start_gen = 0
        pop = pop_gen(mu)
        best_fitness_per_gen = []
        Fs = []
        succ_m_count = 0

    # Barra de progreso desde la generación inicial hasta gens
    with tqdm(total=gens - start_gen, desc="Generaciones", initial=start_gen, leave=True) as pbar_gens:
        for gen in range(start_gen, gens):
            children = []

            # Evaluar la población actual y obtener el mejor individuo
            pop = [{'individual': parent['individual'], 'fitness': target_func(parent['individual'])} for parent in pop]
            best_parent = max(pop, key=lambda x: x['fitness'])

            for i in range(lamb):
                parent = pop[i]['individual']

                # Mapear el individuo a valores reales
                parent_unit = convert_individual(parent)
                best_parent_c = convert_individual(best_parent['individual'])

                # Mecanismo de mutación y reparación
                x2, x3 = random.sample(pop, 2)
                x2 = convert_individual(x2['individual'])
                x3 = convert_individual(x3['individual'])
                u = []
                for j in range(len(best_parent_c)):
                    u.append(best_parent_c[j] + F * (x2[j] - x3[j]))
                u = fixArch(convert_individual(u, to_real=False))
                u = convert_individual(u)

                # Operador de recombinación
                cr_points = get_cr_points(rp, len(parent))
                child = [u[j] if j in cr_points else parent[j] for j in range(len(u))]
                child = fixArch(convert_individual(child, to_real=False))

                children.append({'individual': child, 'fitness': 0})

            # Calcular fitness para cada hijo
            children = [{'individual': child['individual'], 'fitness': target_func(child['individual'])} for child in children]

            # Combinar la población actual y la descendencia
            complete_pop = pop + children

            if auto_adapt:
                # Contar mutaciones exitosas
                succ_m_count += get_succ_m(pop, children)

                # Adaptar F cada n generaciones
                if (gen + 1) % n == 0:
                    Fs.append(F)
                    ps = succ_m_count / (n * lamb)
                    if ps > 1/5:
                        F /= 0.817
                    elif ps < 1/5:
                        F *= 0.817
                    succ_m_count = 0

            # Seleccionar los mejores mu individuos para la siguiente generación
            pop = sorted(complete_pop, key=lambda x: x['fitness'], reverse=True)[:mu]
            best_fitness_per_gen.append(max(pop, key=lambda x: x['fitness'])['fitness'])

            # Guardar checkpoint cada 100 generaciones o al final del experimento
            if (gen + 1) % 100 == 0 or (gen == gens - 1):
                checkpoint_state = {
                    "current_generation": gen,
                    "population": pop,
                    "best_fitness_per_gen": best_fitness_per_gen,
                    "Fs": Fs,
                    "F": F,
                    "succ_m_count": succ_m_count
                }
                checkpoint_filename = os.path.join(checkpoint_dir, f"{exp}_{gen}.pkl")
                with open(checkpoint_filename, "wb") as f_checkpoint:
                    pickle.dump(checkpoint_state, f_checkpoint)

            pbar_gens.update(1)

    best_element = max(pop, key=lambda x: x['fitness'])
    Fs.append(F)

    # Guardar checkpoint final con el resumen del experimento para graficar
    final_state = {
        "best_element": best_element,
        "best_fitness_per_gen": best_fitness_per_gen,
        "Fs": Fs
    }
    final_checkpoint_filename = os.path.join(checkpoint_dir, f"{exp}_final.pkl")
    with open(final_checkpoint_filename, "wb") as f_final:
        pickle.dump(final_state, f_final)

    return best_element, best_fitness_per_gen, Fs

from google.colab import drive
drive.mount('/content/drive')

import joblib

# Cargar el modelo desde el archivo
model = joblib.load("/content/drive/MyDrive/NAS/surr_m_4_ec/xgboost_best_model_pca.pkl")
#model = joblib.load("/content/xgboost_best_model_pca.pkl")

import copy

def eval_arch(ind):
  ind_c = copy.deepcopy(ind)
  reshaped_ind_c = np.array(ind_c).reshape(1, -1)
  acc = model.predict(reshaped_ind_c)
  return acc[0]

import copy
import numpy as np

def eval_arch(ind):
    # Hacemos una copia profunda y seleccionamos solo los primeros 12 componentes
    ind_c = copy.deepcopy(ind)[:12]
    reshaped_ind_c = np.array(ind_c).reshape(1, -1)
    acc = model.predict(reshaped_ind_c)
    return acc[0]



from tqdm import tqdm

best_models = []
all_best_fitness = []
F_arr = []
# Agregar tqdm para mostrar progresoa
for i in tqdm(range(30), desc="Running Experiments"):
    best_model, best_fitness_per_gen, Fs = es(
        eval_arch,
        gens=2000,
        F=0.5,
        mu=5000,
        auto_adapt=True,
        exp=i,
        resume=True

    )
    F_arr.append(Fs)
    best_models.append(best_model)
    all_best_fitness.append(best_fitness_per_gen)

best_models

def build_tf_model_from_dict(model_dict, input_shape=(128, 128, 3), verbose=False):
    """
    Construye un modelo de TensorFlow a partir de un diccionario de arquitectura, sin usar clases personalizadas.

    Tipos de capas soportadas:
      - 'Conv2D', 'DepthwiseConv2D', 'BatchNorm', 'MaxPooling',
        'Flatten', 'Dense', 'Dropout', 'DontCare', 'SelfAttention'

    Args:
        model_dict: diccionario con la definición de capas.
        input_shape: forma de la entrada (altura, anchura, canales).
        verbose: si True, muestra mensajes de depuración.

    Retorna:
        Un objeto tf.keras.Model.
    """
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs

    # Conversión de canales si es necesario: si la entrada no tiene 4 canales, se ajusta.
    target_in_channels = 4
    if input_shape[-1] != target_in_channels:
        if verbose:
            print(f"Insertando capa de conversión: de {input_shape[-1]} a {target_in_channels} canales.")
        x = tf.keras.layers.Conv2D(target_in_channels, kernel_size=1, padding='same')(x)

    # Recorrer las capas del diccionario
    for layer in model_dict['layers']:
        if layer['type'] == 'Conv2D':
            x = tf.keras.layers.Conv2D(filters=layer['filters'],
                                       kernel_size=3,
                                       strides=layer['strides'],
                                       padding='same')(x)
            if layer['activation'].lower() == "relu":
                x = tf.keras.layers.ReLU()(x)
            else:
                x = tf.keras.layers.LeakyReLU()(x)

        elif layer['type'] == 'DepthwiseConv2D':
            x = tf.keras.layers.DepthwiseConv2D(kernel_size=3,
                                                strides=layer['strides'],
                                                padding='same')(x)
            x = tf.keras.layers.Activation(layer['activation'])(x)

        elif layer['type'] == 'BatchNorm':
            x = tf.keras.layers.BatchNormalization()(x)

        elif layer['type'] == 'MaxPooling':
            x = tf.keras.layers.MaxPooling2D(pool_size=2,
                                             strides=layer['strides'],
                                             padding='same')(x)

        elif layer['type'] == 'Flatten':
            x = tf.keras.layers.Flatten()(x)

        elif layer['type'] == 'Dense':
            x = tf.keras.layers.Dense(units=layer['units'],
                                      activation=layer['activation'])(x)

        elif layer['type'] == 'Dropout':
            x = tf.keras.layers.Dropout(rate=layer['rate'])(x)

        elif layer['type'] == 'DontCare':
            x = tf.identity(x)

        elif layer['type'] == 'SelfAttention':
            desired_filters = layer['filters']
            # Ajustar canales si es necesario.
            if x.shape[-1] != desired_filters:
                if verbose:
                    print(f"Ajustando canales en SelfAttention: {x.shape[-1]} -> {desired_filters}")
                x = tf.keras.layers.Conv2D(filters=desired_filters,
                                           kernel_size=1,
                                           padding='same')(x)
            window_size = layer.get('window_size', 16)
            attention_heads = layer.get('attention_heads', 4)
            # Uso de Lambda con argumento output_shape para evitar el error.
            x = tf.keras.layers.Lambda(
                lambda t: self_attention_block(t, filters=desired_filters,
                                               window_size=window_size,
                                               attention_heads=attention_heads,
                                               verbose=verbose),
                output_shape=lambda s: (s[0], s[1], s[2], desired_filters)
            )(x)
        else:
            if verbose:
                print(f"Tipo de capa desconocido: {layer['type']}. Se omite.")

    model = tf.keras.Model(inputs=inputs, outputs=x)
    return model

import matplotlib.pyplot as plt

# Determine the maximum number of generations across all runs
max_generations = max(len(fitness) for fitness in all_best_fitness)
generations = np.arange(1, max_generations + 1)

# Initialize a matrix to hold all fitness values, handling varying lengths
fitness_matrix = np.full((30, max_generations), np.nan)

for i, best_fitness_per_gen in enumerate(all_best_fitness):
    fitness_length = len(best_fitness_per_gen)
    fitness_matrix[i, :fitness_length] = best_fitness_per_gen

# Plot all runs in light gray
plt.figure(figsize=(12, 8))
for i in range(30):
    plt.plot(
        generations,
        fitness_matrix[i],
        linestyle='-',
        color='red',
        alpha=0.5
    )

# Compute the mean and standard deviation across runs at each generation
mean_fitness = np.nanmean(fitness_matrix, axis=0)
std_fitness = np.nanstd(fitness_matrix, axis=0)

# Plot the mean best fitness
plt.plot(
    generations,
    mean_fitness,
    linestyle='-',
    color='blue',
    label='Mean Accuracy'
)

# Fill the area between (mean - std) and (mean + std)
plt.fill_between(
    generations,
    mean_fitness - std_fitness,
    mean_fitness + std_fitness,
    color='blue',
    alpha=0.2,
    label='Standard Deviation'
)

plt.title('Convergence Plot of Accuracy per Generation over 30 Runs')
plt.xlabel('Generations')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

# Parameters
n = 10       # Adaptation interval (every n generations)
gens = 1000  # Total number of generations
num_runs = 30  # Number of runs

# Plotting
plt.figure(figsize=(12, 6))

for Fs in F_arr:
    # Generations where F was recorded
    generations = [n * i for i in range(1, len(Fs))]
    generations.append(generations[-1] + 1)
    # Adjust the last generation if it doesn't align with n
    if generations[-1] != gens:
        generations[-1] = gens
    plt.plot(generations, Fs, alpha=0.3, color='blue')

# Calculate and plot the mean F value at each adaptation point
max_length = max(len(Fs) for Fs in F_arr)

# Pad shorter Fs lists if necessary
Fs_padded = []
for Fs in F_arr:
    padding_length = max_length - len(Fs)
    Fs_padded.append(Fs + [Fs[-1]] * padding_length)

mean_Fs = [sum(Fs[i] for Fs in Fs_padded) / num_runs for i in range(max_length)]
mean_generations = [n * i for i in range(1, max_length)]
mean_generations.append(mean_generations[-1] + 1)
# Adjust the last generation if necessary
if mean_generations[-1] != gens:
    mean_generations[-1] = gens

plt.plot(mean_generations, mean_Fs, color='red', linewidth=2, label='Mean F Value')

# Label the axes and add a title
plt.xlabel('Generation')
plt.ylabel('F Value')
plt.title('Progress of F over Generations across 30 Runs')
plt.grid(True)
plt.legend(loc='upper right')

# Display the plot
plt.show()

best_model = max(best_models, key=lambda x: x['fitness'])
best_model['fitness']

# prompt: de best_models, dame aquellos top 3 moodelos con ssu individual y su score, que tengan individual diferente (único) y que tengan el fitnes má sgrande (de mayor a menor)

# Sort the best_models list by fitness in descending order and then select top 3 with unique individuals
top_3_models = sorted(best_models, key=lambda x: x['fitness'], reverse=True)
unique_individuals = set()
final_top_3 = []

for model in top_3_models:
    # Convert the list to a tuple before checking if it's in the set
    individual_tuple = tuple(model['individual'])
    if individual_tuple not in unique_individuals:
        final_top_3.append(model)
        unique_individuals.add(individual_tuple)
    if len(final_top_3) == 3:
        break

# Print the top 3 models
for model in final_top_3:
    print(f"Individual: {model['individual']}, Score: {model['fitness']}")
for model in final_top_3:
    print(f"{model['individual']},")

print(best_model['individual'])



model_dict = decode_model_architecture(best_model['individual'])
model_dict

cnn = build_tf_model_from_dict(model_dict)
cnn

cnn.save('/drive/MyDrive/NAS/EC_Project/best_model_mu100_gens1000_F0p5_5000mu_autoadapt.h5')

cnn.save('/drive/MyDrive/NAS/EC_Project/best_model_mu100_gens1000_F0p5_5000mu_autoadapt.keras')